apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-zwrn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-zwrn
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-zwrn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-zwrn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-zwrn
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ziqs-tenant/rhtap-demo-app/hacbs-test-project-zwrn@sha256:51578672136953bada48b6e36c91f73cf8f919c777b131291c1c87af92cf15aa
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
